sudo: required

dist: trusty

language: node_js

node_js:
  - '8.11.4'

cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache/Cypress
matrix:
  allow_failures:
    #
jobs:
  include:
    - stage: test
      name: 'Test'
      install:
        - yarn
        - yarn global add cypress@3.5.0
        - cypress install
        - yarn global add ganache-cli@6.1.8
        - yarn global add wait-on
      before_script:
        - ganache-cli >ganache.log 2>&1 &
        - sleep 5
      script: 'yarn cypress:ci'
    - stage: deploy
      name: 'Deploy to live'
      script: yarn deploy

stages:
  - name: test
    if: branch != master
  - name: deploy
    if: branch = master

notifications:
  email: false
